name: ü¶ú Publish Canary

on:
  push:
    branches: [feature/cognito-auth-provider]
    # We don't want this to run on release
    tags-ignore: ['v**']
    # No need to run on docs-only changes
    paths-ignore: ['docs/**']

jobs:
  publish-canary:
    name: ü¶ú Publish Canary
    if: github.repository == 'stafflink-pty-ltd/redwood'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.value }}
    steps:
      - uses: actions/checkout@v3
        # `fetch-depth`‚Äînumber of commits to fetch. `0` fetches all history for all branches and tags.
        #  This is required because lerna uses tags to determine the version.
        with:
          fetch-depth: 0

      - name: üß∂ Setup job
        uses: ./.github/actions/setup_job

      - name: ‚úÖ Check constraints, dependencies, and package.json's
        uses: ./tasks/check

      - name: üèó Build
        run: yarn build

      - name: üîé Lint
        run: yarn lint

      - name: üß™ Test
        run: yarn test

      - name: üö¢ Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          yarn lerna publish --include-merged-tags \
                             --canary \
                             --preid canary \
                             --dist-tag canary \
                             --force-publish \
                             --loglevel verbose \
                             --no-git-reset \
                             --yes
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: üè∑ Get version
        id: get-version
        uses: sergeysova/jq-action@v2.1.0
        with:
          cmd: 'jq .version packages/core/package.json -r'
